server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: arco-design-server
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 512MB #限制文件上传大小为10M
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        #表名及字段全小写下划线分隔命名策略(默认)
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    excluded-view-names: ''
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  mail:
    host: smtp.163.com
    nickname: ArcoDesign
    username: 15233088662@163.com
    password: your authorization code
    properties.mail.smtp.port: 994
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: top.qiudb.module.*.domain.entity
  type-enums-package: top.qiudb.common.constant
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false

sa-token:
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  is-print: false

sms:
  aliyun:
    accessKeyId: your accessKeyId
    accessKeySecret: your accessKeySecret
    templateCode: SMS_215344833
    signName: 花卷买卖

# 沙箱配置
alipay:
  appid: 2016110200787593
  privateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDYjcBKrMlFIeYbEgq1zDH3Vxk4C5M3mE96xIAWu4OwPJOvauWkiu5tintpl0IrJJDCeCtHS19oPpwxwrbocFDfRuF7FJGiWCSwdPCvLihUScXVvwVBGktgNkrZBuJkXQNZRCN4aJSzHYjV+EG0Wnm0rX8rAz3JXO1Ejlv4O4Ql/n/FEJP/hoOFCXXfjReVP5Gn9Zt+r9mOlhJs2UT9LmqIffn3AKQudy73496F3gKiQzXkg7QYAF7c63zsKoCpd+ycJtAhCbblWSfZ+JtMBqLZ+qMZvi7cDCUxMv+0nQUMjn8Mj1Njy+0L1aI6hm1Y1sEkK1kSqrV3kMoU038eBDdHAgMBAAECggEBAIgEoR9GYDU4EZw3PNrrowbEgmadfp6Q4HswKXQd2506r1ijQBKV4SSUsuejxj/q+7HqYOSrBwYnLVxj/RcKVQGpN79jMAZUbtcW3IZr65DltYmILfiyV13bPDANDu4TLiNHlS/wIFZQ2r3q7PonSgKeZx3RL2HnKHDDKilE2MAzbp/RLeKDxHHwoGL5pso5O6AFW+Uf+LSlmrXF9TUanxH8yegYdOLuSnRsbeWQ2gTuyJ/kPwmLSJRS56Rg/GjxMhF3F/xOGkF5YSFnt+KnCofNu8bMu1rOtU0qQG6Ho5AveoPH33QC9Zq31WArAFGnsANi3gGK33RklTS+Me5DTmECgYEA7/w8Nu1Bnn1ZxhAr4ePW8i7ceZVaq7hSYXGYpiYrH4EcWN8bH/lXcRdRDGCHuip3UpIJhbIow082bYVr7BeJLlZC9nBR1BA7rA2hcgnBavdnORkQeLpR64/9YpN+uv3jAeg8iVh3DdiTA6E9Jigr0sVC7tKSH+DKfWYP5euvqQsCgYEA5wE5kue4gBjYGJDaeEMh/Pl6RjCz/tE5ntnD2SfDAxu0vbIDoqKCZEgQp5hllZ9ejD06R/v0gB4dw479dlVmJ5tVDW+0PPxyUd1ZtyMukt050B2hlVkQXtH+hzVqshcb3L7QZLl/v4wiNJOpcjJiVRCnlEnXjU9OKbLY80uFqDUCgYEAvfb3Hy99gtyMxJimc9/rlLd9dIzCQi3coB/Qiqyp8/06mCq7CPtRuUaQtHBw3++flm/dM8SMOdYpKlaz0CXtRA2qYfMVAv16jr4XbvLD9U0zm2H4xOgP0pyfIXnJlnFEUY0o5jttujsWXIg0pFCmJ+hYDD4Ix00kXFD/Aqwm13MCgYBGKFkUBMxEG0eGLngrjjgEXMCGEMSZ33FgjUKt8SWJDCEYe7ge7LwtOLXWMLKpfn14mh/ZPOxE/OCNRCA2kDk2TjbGneZfn0wZEODufgDnGck1K8qnUSVnpt9msRJ2hA4yPMGN1ci2pBi/XxlXVXYH38cFgme0wyE6CNdbDNTLAQKBgQC+ukY54XllKzqEg7/3Ifp2WsgPXHlvITgYoLqvWfUVZc858nZV7YtMGoAqvYAlMUzakLbGj79HQLEjpG3bKY+tQ1N311IKZUnaa3OdC2FMvwNivmksHdV6mZXXZSr3zb2bgXRPo8Xyaxp2FdVqGSRb4QgGfErjyuqh1ejZqXOeSw==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3oN26u6vw0TaiE8fkHpKerphbDlFtguH9TRQeYppBrZzYnxZhRv2s7Skk2hpnyUcFx7JOL8Oon6d2sTy25qFoUudYHk5xz7duKajbImZ4PeBprhGM+oRGLxgNyyftP3O6Et77PGJEIvdy6BIA4Z+DYihC0JjIyHad+XNF4jOWo9oEskplldcU23M1Qj0r4nCgWQm+jgOk+kigj5jxa4+qarMXFEIEkPvGNu3Io/uI2u/BFiGyj894VQ81IV119G1jiBWZ4REt72FlADYGhhcILXdKJTUw7i+bg+3kieOk9JQkoRi+9zaIubuRTkEdcnol0c8Ln/PjAfPTjQF0bKfcwIDAQAB
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  returnUrl: http://192.168.8.145:8080/api/third/pay/success
  # 异步回调接口必须使用公网地址
  notifyUrl: http://3168593q4j.zicp.vip/api/third/pay/notify
  redirectUrl: http://192.168.8.145:8080/api/doc.html

redis:
  key:
    prefix:
      authCode: "auth-code:"
    expire:
      # 验证码超期时间10分钟
      authCode: 600

swagger:
  enable: true
  name: ma_ying_fa
  url: https://gitee.com/ma_ying_fa
  email: qiudb.top@aliyun.com

secure:
  ignored:
    urls:
      - /admin/register
      - /admin/login/username
      - /admin/login/phone
      - /third/message/**
      - /third/pay/**
      - /static/**
      - /doc.html
      - /webjars/**
      - /swagger-resources/**
      - /v3/api-docs
